version: '3'
services:
   webserver:
     image: 177635644561.dkr.ecr.us-east-1.amazonaws.com/new-nginx-webapp:latest
     container_name: webserver
     restart: unless-stopped
     logging:
        driver: awslogs
        options:
            awslogs-group: demo-cluster
            awslogs-region: us-east-1
            awslogs-stream-prefix: nginx
     ports:
       - "80:80"   
